apiVersion: v1
kind: Service
metadata:
  name: ollama-mac
  namespace: langflow
  annotations:
    tailscale.com/tailnet-fqdn: "mac.tail651fca.ts.net"
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: ollama
      port: 11434
      protocol: TCP
